name: Deploy to Production

on:
  pull_request:
    branches:
      - production
    types:
      - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: main
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Main Environment
        run: echo "Deploying to Production Environment..."